### ISSUE TITLE
Color enums

### ISSUE THREAD

**Issue by mgord9518** [MoAlyousef/zfltk#4]
Zig does not appear to offer implicit conversion from enums to their underlying types. I've run into this issue as converting a u32 into an enum explicitly doesn't allow for values that aren't defined as values set in the enum, which becomes a problem when setting custom RGB colors.

Do you think a good solution would just be to change all color functions to use u32 as well (or offer enum-specific functions)? I've noticed as it is currently, it's a mixture of both

**Comment by MoAlyousef** [comment]
Hi
At some point Color was defind as:
```zig
pub const Color = enum(u32) 
```
This was changed to a struct. 
I had planned to add methods to it which would accept RGB values. These could then be used with widget methods taking Color.
I didn't get yet to refactoring the rest of the code.

As to my preference, I would prefer to stick with a Color struct, since the FLTK color representation (RGBI) is a bit unintuitive.

**Comment by MoAlyousef** [comment]
I've pushed a proof of concept. The changes might be a lot, but it's to make zfltk build with latest zig.
